#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

sudo apt-get update
apt-get install -y haproxy

# edit config file
server_config=\
"
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 6452-web-01 100.25.196.169:80 check
        server 6452-web-02 3.84.255.205:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restart nginx to apply settings
sudo service haproxy restart
